### ISSUE TITLE
which framework to work on Aisis-Framework OR Freya

### ISSUE THREAD

**Issue by ajayphp** [AdamKyle/Freya#1]
Hi, 
Its seems gr8 work done by you, 
I am confused which framework to work on Aisis-Framework OR Freya 
to use , Freya is exteneded of Aisis or ? 

Please advice ?

Regards,
Ajay

**Comment by AdamKyle** [comment]
Hello, sorry for the late reply. Freya is the one to work on. All commits come to this repo. Aisis Framework is deprecated and essentially turned into this project.
